const Player = (playerType, enemyBoard) => {
  // playerType will be either string value 'human' or 'AI'
  // enemyBoard is board array from Gameboard object

  const chooseTarget = function chooseCoordinatesToAttack(row, column) {
    /*
        chooseTarget returns coordinates to attack if position has not been attacked yet
        If position has been attacked, return false

        If Player is human, coordinates will be passed to function when called
        If Player is AI, coordinates will be randomly generated by below if statement
    */
    // if (playerType === 'AI'){ randomly generate coordinates from 0 to 9}

    if (enemyBoard[row][column] === 'miss' || enemyBoard[row][column] === -1) {
      return false;
    }
    return [row, column];
  };

  return { playerType, enemyBoard, chooseTarget };
};

export { Player };
