const Player = (playerType, enemyBoard) => {
  // playerType will be either string value 'human' or 'AI'
  // enemyBoard is board array from Gameboard object

  const chooseTarget = function chooseCoordinatesToAttack(row, column) {
    /*
        chooseTarget returns coordinates to attack if position has not been attacked yet
        If position has been attacked, return false

        If Player is human, coordinates will be passed to function when called
        If Player is AI, coordinates will be randomly generated by below if statement
    */

    if (playerType === 'AI') {
      // Run this if Player is AI

      // Create random coordinate variables
      let randomRow;
      let randomColumn;

      do {
        /*
          Randomly generate row and column
          Keep running this do while loop if enemy board has already been hit at
          randomly generated row and column
        */
        randomRow = Math.floor(Math.random() * 10);
        randomColumn = Math.floor(Math.random() * 10);
      } while (
        enemyBoard[randomRow][randomColumn] === 'miss' ||
        enemyBoard[randomRow][randomColumn] === -1
      );
      // Once a target that has not been hit has been generated, return it
      return [randomRow, randomColumn];
    }

    // Below only runs if Player is not AI, i.e. if Player is human
    if (enemyBoard[row][column] === 'miss' || enemyBoard[row][column] === -1) {
      /*
        If human player's chosen target has already been hit, return boolean false
        This will force player to choose target again
      */
      return false;
    }
    // If human player has choosen target that has not been hit, return it
    return [row, column];
  };

  return { playerType, enemyBoard, chooseTarget };
};

export { Player };
